apiVersion: v1
kind: Service
metadata:
  name: flask-app-nube
spec:
  selector:
    app: flask-app-nube
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

